title: "celo - go-ethereum fork diff overview"
footer: |
  Fork-diff overview of [`celo`](https://github.com/celo-org/celo-blockchain), a fork of [`go-ethereum`](https://github.com/ethereum/go-ethereum).
base:
  name: go-ethereum
  url: https://github.com/ethereum/go-ethereum
  ref: HEAD  # the specific forked commit is checked out as part of the GitHub workflow
fork:
  name: celo
  url: https://github.com/celo-org/celo-blockchain
  ref: HEAD
def:
  title: "celo-blockchain"
  description: |
    This is an overview of the changes in [`celo-blockchain`](https://github.com/celo-org/celo-blockchain),
    a fork of [`go-ethereum`](https://github.com/ethereum/go-ethereum).

    To minimize changes in this diff, we have replaced `github.com/celo-org/celo-blockchain`
    with `github.com/ethereum/go-ethereum` in imports, removed "ethereum" named imports,
    and applied `gofmt` to both codebases.
    When using individual diffs, double check any changes in the original codebases.

    Since the diffs between the two codebases are currently so large, the categories
    below often reflect different packages as opposed to broader features or logical units.
  sub:
    - title: "accounts"
      globs:
        - "accounts/accounts.go"
        - "accounts/manager.go"
      sub:
        - title: "external"
          globs:
          - "accounts/external/*"
        - title: "keystore"
          globs:
          - "accounts/keystore/*"
        - title: "hd"
          globs:
          - "accounts/hd.go"
          - "accounts/hd_test.go"
        - title: "usbwallet"
          globs:
            - "accounts/usbwallet/*"
            - "accounts/usbwallet/*/*"
        - title: "abi"
          globs:
          - "accounts/abi/*"
          - "accounts/abi/bind/*"
          - "accounts/abi/bind/*/*"
          - "accounts/abi/bind_v2/*"
        - title: "scwallet"
          globs:
          - "accounts/scwallet/*"
    - title: "cmd"
      sub:
        - title: "geth"
          globs:
            - "cmd/geth/*"
            - "cmd/geth/*/*"
            - "cmd/geth/*/*/*"
        - title: "bootnode"
          globs:
            - "cmd/bootnode/*"
        - title: "utils"
          globs:
            - "cmd/utils/*"
        - title: "abigen"
          globs:
            - "cmd/abigen/*"
        - title: "uptime"
          globs:
            - "cmd/uptime/*"
        - title: "clef"
          globs:
            - "cmd/clef/*"
            - "cmd/clef/*/*"
            - "cmd/clef/*/*/*"
        - title: "evm"
          globs:
            - "cmd/evm/*"
            - "cmd/evm/*/*"
            - "cmd/evm/*/*/*"
            - "cmd/evm/*/*/*/*"
        - title: "blspopchecker"
          globs:
            - "cmd/blspopchecker/*"
        - title: "devp2p"
          globs:
            - "cmd/devp2p/*"
            - "cmd/devp2p/*/*"
            - "cmd/devp2p/*/*/*"
            - "cmd/devp2p/*/*/*/*"
        - title: "faucet"
          globs:
            - "cmd/faucet/*"
        - title: "puppeth"
          globs:
            - "cmd/puppeth/*"
            - "cmd/puppeth/*/*"
    - title: "common"
      globs:
        - "common/*"
        - "common/*/*"
        - "common/*/*/*"
        - "common/*/*/*/*"
    - title: "consensus"
      globs:
        - "consensus/*"
        - "consensus/consensustest/*"
      sub:
        - title: "istanbul"
          description: |
            Celo implements Istanbul BFT, specified in the [Celo IBFT Spec](https://github.com/celo-org/celo-blockchain/blob/dbd09899efecd39651f6546a2a42a76bf1667ec3/consensus/istanbul/celo-ibft-spec.md), and loosely based off of [EIP 650](https://github.com/ethereum/EIPs/issues/650).
            This section is almost entirely Celo-specific.
          globs:
            - "consensus/istanbul/*"
            - "consensus/istanbul/*/*"
            - "consensus/istanbul/*/*/*"
            - "consensus/istanbul/*/*/*/*"
        - title: "misc"
          globs:
            - "consensus/misc/*"
        - title: "ethash"
          globs:
            - "consensus/ethash/*"
        - title: "clique"
          globs:
            - "consensus/clique/*"
    - title: "console"
      globs:
        - "console/*"
    - title: "contracts"
      globs:
        - "contracts/*"
        - "contracts/abis/*"
        - "contracts/blockchain_parameters/*"
        - "contracts/checkpointoracle/*"
        - "contracts/checkpointoracle/contract/*"
        - "contracts/currency/*"
        - "contracts/election/*"
        - "contracts/epoch_rewards/*"
        - "contracts/freezer/*"
        - "contracts/gasprice_minimum/*"
        - "contracts/gold_token/*"
        - "contracts/random/*"
        - "contracts/reserve/*"
        - "contracts/testutil/*"
        - "contracts/validators/*"
    - title: "core"
      globs:
        - "core/*"
        - "core/forkid/*"
        - "core/asm/*"
        - "core/state/*"
      sub:
        - title: "rawDB"
          globs:
            - "core/rawdb/*"
        - title: "types"
          globs:
            - "core/types/*"
        - title: "vm"
          globs:
            - "core/vm/*"
            - "core/vm/*/*"
          sub:
            - title: "testdata"
              globs:
                - "core/vm/testdata/*/*"
        - title: "miner"
          globs:
            - "miner/*"
          sub:
            - title: "Miner stress tests"
              globs:
              - "miner/stress/*/*"
        - title: "p2p"
          globs:
            - "p2p/*"
            - "p2p/*/*"
            - "p2p/*/*/*"
    - title: "crypto"
      globs:
        - "crypto/*"
      sub:
        - title: "bls"
          globs:
            - "crypto/bls/*"
        - title: "bls12377"
          globs:
            - "crypto/bls12377/*"
        - title: "bls12381"
          globs:
            - "crypto/bls12381/*"
        - title: "blake2b"
          globs:
            - "crypto/blake2b/*"
        - title: "bn256"
          globs:
            - "crypto/bn256/*"
            - "crypto/bn256/*/*"
        - title: "blake2s"
          globs:
            - "crypto/blake2s/*"
    - title: "eth"
      globs:
        - "eth/*"
      sub:
        - title: "catalyst"
          globs:
            - "eth/catalyst/*"
        - title: "downloader"
          globs:
            - "eth/downloader/*"
        - title: "ethconfig"
          globs:
            - "eth/ethconfig/*"
        - title: "fetcher"
          globs:
            - "eth/fetcher/*"
        - title: "filters"
          globs:
            - "eth/filters/*"
        - title: "gasprice"
          globs:
            - "eth/gasprice/*"
        - title: "protocols"
          globs:
            - "eth/protocols/*"
            - "eth/protocols/*/*"
            - "eth/protocols/*/*/*"
        - title: "tracers"
          globs:
            - "eth/tracers/*"
            - "eth/tracers/*/*"
            - "eth/tracers/*/*/*"
    - title: "ethclient"
      globs:
        - "ethclient/*"
        - "ethclient/*/*"
    - title: "ethstats"
      globs:
        - "ethstats/*"
    - title: "graphql"
      globs:
        - "graphql/*"
    - title: "internal"
      globs:
        - "internal/*"
        - "internal/*/*"
        - "internal/*/*/*"
    - title: "les"
      globs:
        - "les/*"
      sub:
        - title: "fetcher"
          globs:
            - "les/fetcher/*"
        - title: "downloader"
          globs:
            - "les/downloader/*"
        - title: "flowcontrol"
          globs:
            - "les/flowcontrol/*"
    - title: "light"
      globs:
        - "light/*"
    - title: "metrics"
      globs:
        - "metrics/*"
    - title: "mobile"
      globs:
        - "mobile/*"
    - title: "mycelo"
      description: |
        [mycelo](https://github.com/celo-org/celo-blockchain/blob/dbd09899efecd39651f6546a2a42a76bf1667ec3/cmd/mycelo/README.md) is a developer tool to run blockchain testnets with Celo Core Contracts already deployed.
        This is entirely specific to the Celo blockchain.
      globs:
        - "mycelo/*"
        - "mycelo/*/*"
        - "mycelo/*/*/*"
        - "mycelo/*/*/*/*"
        - "cmd/mycelo/*"
    - title: "node"
      globs:
        - "node/*"
    - title: "params"
      globs:
        - "params/*"
    - title: "rpc"
      globs:
        - "rpc/*"
    - title: "shared signer"
      globs:
        - "shared/signer/*"
      sub:
        - title: "testdata"
          globs:
            - "shared/signer/testdata/*"
            - "shared/signer/testdata/*/*"
    - title: "signer"
      globs:
        - "signer/*"
        - "signer/*/*"
        - "signer/*/*/*"
        - "signer/*/*/*/*"
    - title: "tests, e2e_test"
      globs:
        - "test/*"
        - "tests/*"
        - "tests/*/*"
        - "tests/*/*/*"
        - "tests/*/*/*/*"
        - "e2e_test/*"
        - "e2e_test/*/*/*"
# ignored globally, does not count towards line count
ignore:
  # Double ** globbing is not currently available
  - ".circleci/*"
  - ".github/*"
  - ".github/*/*"
  # Configuration files in root
  - ".git*"
  - "*.yaml"
  - "*.yml"
  - "*.md"
  - "Dockerfile*"
  - ".dockerignore"
  - "*.sum"
  - "go.mod"
  - ".mailmap"
  - "AUTHORS"
  - "COPYING"
  - "COPYING.LESSER"
  - "Makefile"
  - "default.profraw"
  - "geth-sources.jar"
  - "monorepo_commit"
  - "oss-fuzz.sh"
  - "scripts/*"
  - "scripts/*/*"
  # Docs
  - "docs/*"
  - "docs/*/*"
  - "docs/*/*/*"
  - "docs/*/*/*/*"
  # This is one layer deeper than currently exists
  - "docs/*/*/*/*/*"
  - "e2e_test/ethersjs-api-check/*.json"
  - "e2e_test/ethersjs-api-check/*/*.json"
  - "e2e_test/ethersjs-api-check/.gitignore"
