title: "celo - go-ethereum fork diff overview"
footer: |
  Fork-diff overview of [`celo`](https://github.com/celo-org/celo-blockchain), a fork of [`go-ethereum`](https://github.com/ethereum/go-ethereum).
base:
  name: go-ethereum
  url: https://github.com/ethereum/go-ethereum
  hash: eae3b1946a276ac099e0018fc792d9e8c3bfda6d
fork:
  name: celo
  url: https://github.com/celo-org/celo-blockchain
  ref: refs/heads/paul/forkdiff
def:
  title: "celo"
  description: |
    This is an overview of the changes in [`celo`](https://github.com/celo-org/celo-blockchain),
    a fork of [`go-ethereum`](https://github.com/ethereum/go-ethereum).
  sub:
    - title: "Core modifications"
      sub:
        - title: "Consensus"
          globs:
            - "consensus/*"
            - "consensus/consensustest/*"
            - "consensus/istanbul/*"
            - "consensus/istanbul/announce/*"
            - "consensus/istanbul/backend/*"
            - "consensus/istanbul/backend/backendtest/*"
            - "consensus/istanbul/backend/internal/*"
            - "consensus/istanbul/backend/internal/replica/*"
            - "consensus/istanbul/core/*"
            - "consensus/istanbul/db/*"
            - "consensus/istanbul/proxy/*"
            - "consensus/istanbul/uptime/*"
            - "consensus/istanbul/validator/*"
            - "consensus/istanbul/validator/random/*"
            - "consensus/misc/*"
    - title: "mycelo"
      globs:
        - "mycelo/*"
        - "mycelo/cluster/*"
        - "mycelo/contract/*"
        - "mycelo/env/*"
        - "mycelo/genesis/*"
        - "mycelo/hdwallet/*"
        - "mycelo/internal/*"
        - "mycelo/internal/console/*"
        - "mycelo/internal/scripts/*"
        - "mycelo/internal/scripts/generate/*"
        - "mycelo/internal/utils/*"
        - "mycelo/loadbot/*"
    - title: "Contracts"
      globs:
        - "contracts/*"
        - "contracts/abis/*"
        - "contracts/blockchain_parameters/*"
        - "contracts/checkpointoracle/*"
        - "contracts/checkpointoracle/contract/*"
        - "contracts/currency/*"
        - "contracts/election/*"
        - "contracts/epoch_rewards/*"
        - "contracts/freezer/*"
        - "contracts/gasprice_minimum/*"
        - "contracts/gold_token/*"
        - "contracts/random/*"
        - "contracts/reserve/*"
        - "contracts/testutil/*"
        - "contracts/validators/*"
    - title: "Tests"
      globs:
        - "test/*"
        - "tests/*"
        - "tests/fuzzers/*"
        - "tests/fuzzers/abi/*"
        - "tests/fuzzers/bitutil/*"
        - "tests/fuzzers/bls12381/*"
        - "tests/fuzzers/bls12381/testdata/*"
        - "tests/fuzzers/bn256/*"
        - "tests/fuzzers/keystore/*"
        - "tests/fuzzers/keystore/corpus/*"
        - "tests/fuzzers/les/*"
        - "tests/fuzzers/les/debug/*"
        - "tests/fuzzers/rangeproof/*"
        - "tests/fuzzers/rangeproof/corpus/*"
        - "tests/fuzzers/rangeproof/debug/*"
        - "tests/fuzzers/rlp/*"
        - "tests/fuzzers/rlp/corpus/*"
        - "tests/fuzzers/runtime/*"
        - "tests/fuzzers/secp256k1/*"
        - "tests/fuzzers/stacktrie/*"
        - "tests/fuzzers/stacktrie/debug/*"
        - "tests/fuzzers/trie/*"
        - "tests/fuzzers/trie/corpus/*"
        - "tests/fuzzers/txfetcher/*"
        - "tests/fuzzers/txfetcher/corpus/*"
        - "tests/fuzzers/vflux/*"
        - "tests/fuzzers/vflux/debug/*"
        - "tests/solidity/*"
        - "tests/solidity/contracts/*"
        - "tests/solidity/migrations/*"
        - "tests/solidity/test/*"
        - "tests/testdata/*"
    - title: "Crypto"
      globs:
        - "crypto/blake2b/*"
        - "crypto/blake2s/*"
        - "crypto/bls/*"
        - "crypto/bls12377/*"
        - "crypto/bls12381/*"
# ignored globally, does not count towards line count
ignore:
  - ".circleci/*"
  - ".github/*"
  - "*.sum"
  - "docs/*"
  # TODO EN: can this not be summarized as docs/**/*?
  - "docs/_data/*"
  - "docs/_includes/*"
  - "docs/_layouts/*"
  - "docs/audits/*"
  - "docs/bin/*"
  - "docs/docs/*"
  - "docs/docs/_clef/*"
  - "docs/docs/_clef/qubes/*"
  - "docs/docs/_dapp/*"
  - "docs/docs/_developers/*"
  - "docs/docs/_getting-started/*"
  - "docs/docs/_install-and-build/*"
  - "docs/docs/_interface/*"
  - "docs/docs/_legacy/*"
  - "docs/docs/_rpc/*"
  - "docs/docs/_whisper/*"
  - "docs/guide/*"
  - "docs/static/*"
  - "docs/static/fonts/*"
  - "docs/static/images/*"
  - "docs/static/images/emoji/*"
  - "docs/static/scripts/*"
  - "docs/static/scripts/custom/*"
  - "docs/static/styles/*"
  - "docs/static/styles/custom/*"
