# This file configures github.com/golangci/golangci-lint.

run:
  timeout: 2m
  tests: true
  # default is true. Enables skipping of directories:
  #   vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-dirs-use-default: true

linters:
  disable-all: true
  enable:
    # - deadcode
    # - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - varcheck

    - goconst
    - goimports
    - gosec
    - misspell
    # - prealloc
    - unconvert
    # - unparam

linters-settings:
  gofmt:
    simplify: true
  goconst:
    min-len: 3 # minimum length of string constant
    min-occurrences: 6 # minimum number of occurrences


issues:
  exclude-rules:
    # ignore deprecation warnings for now
    - linters:
        - staticcheck
      text: "SA1019:"
    # genesis has a really long string
    - path: core/genesis_alloc.go
      linters:
        - misspell
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    - path: crypto/blake2b/
      linters:
        - deadcode
    - path: crypto/bn256/cloudflare
      linters:
        - deadcode
    - path: p2p/discv5/
      linters:
        - deadcode
    - path: core/vm/instructions_test.go
      linters:
        - goconst
