pull_request_rules:
  - name: Automatically merge on CI success and code review
    conditions:
      # Add this label when you are ready to automerge the pull request.       
      - "label=automerge"
      # Exclude drafts
      - "-draft"
      # At least one approval required
      - "#approved-reviews-by>=1"
      # Only enable this when the pull request is being merged into master
      - "base=master"
      # List of all the tests that should pass.
      # Keep this in sync with the github branch protection settings
      - "status-success=ci/circleci: unit-tests"
      - "status-success=ci/circleci: lint"
      - "status-success=ci/circleci: end-to-end-geth-transfer-test"
      - "status-success=ci/circleci: end-to-end-geth-sync-test"
      - "status-success=ci/circleci: end-to-end-geth-slashing-test"
      - "status-success=ci/circleci: end-to-end-geth-governance-test"
      - "status-success=ci/circleci: end-to-end-validator-order-test"
      - "status-success=ci/circleci: end-to-end-geth-blockchain-parameters-test"
    actions:
      merge:
        method: squash 