# Source: https://doc.mergify.io/getting-started.html#configuration
pull_request_rules:
  - name: Automatically merge on CI success and code review
    conditions:
      # Add this label when you are ready to automerge the pull request.       
      - label=automerge
      # At least one approval required
      - "#approved-reviews-by>=1"
      # No pending changes requested
      - "#changes-requested-reviews-by=0"
      # Only enable this when the pull request is being merged into master
      - "base=master"
      # List of all the tests that should pass.
      - "status-success=ci/circleci: end-to-end-sync-test"
      - "status-success=ci/circleci: end-to-end-transfer-test"
      - "status-success=ci/circleci: lint"
      - "status-success=ci/circleci: unit-tests"
    actions:
      merge:
        method: squash
        # https://doc.mergify.io/strict-workflow.html
        strict: smart
      # Delete the branch
      delete_head_branch:        
