secrets:
- kmsKeyName: projects/celo-testnet/locations/global/keyRings/celo-keyring/cryptoKeys/github-key
  secretEnv:
    NPM_TOKEN: CiQAW8JnkilowpBhyESvNfF0vSagXd8Q9eEQLyJz9V4zx/5mBp4STQAZggEuSvsdYbFftiTHSalxCxVRx6I44ptSkGaZJdsvO5vydci0G7fM8cOk5QBTOTPFlaWtmZnHnNekJuCf2LtSWrilSXqy/BP1FUNb
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '--build-arg', 'commit_sha=$SHORT_SHA', '--build-arg', 'npm_token=$$NPM_TOKEN', '-f', 'Dockerfile.androidbuild', '.' ]
  secretEnv: ['NPM_TOKEN']
  waitFor: ["-"]
timeout: 900s
