# This builds the android version and pushes it to NPM
# FROM celohq/android-client
FROM node:latest

ARG commit_sha
ARG NPM_TOKEN

COPY . /go-ethereum
WORKDIR /go-ethereum

RUN bash npm-android.sh $commit_sha $NPM_TOKEN