# This builds the android version and pushes it to NPM
# FROM celohq/android-client
FROM node:latest

ARG commit_sha
ARG npm_token

COPY . /go-ethereum
WORKDIR /go-ethereum

RUN bash npm-android.sh $commit_sha $npm_token