[package]
name = "bls-snark"
version = "0.1.0"
authors = ["Kobi Gurkan <kobigurk@gmail.com>", "Michael Straka <mstraka@celo.org>"]
edition = "2018"

[dependencies]
r1cs-std = { path = "../../zexe/r1cs-std" }
r1cs-core = { path = "../../zexe/r1cs-core" }
algebra = { path = "../../zexe/algebra" }
bls-zexe = { path = "../algebra" }
rand = { version = "0.7" }
byteorder = "1.3.2"
hex = "0.3.2"
log = "0.4.6"

[dev-dependencies]
rand_xorshift = { version = "0.2" }

[lib]
crate-type = ["lib", "staticlib"]