// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package types

import (
	"encoding/json"
	"errors"
	"math/big"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/common/hexutil"
)

var _ = (*TxdataMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (t Txdata) MarshalJSON() ([]byte, error) {
	type Txdata struct {
		AccountNonce        hexutil.Uint64  `json:"nonce"    gencodec:"required"`
		Price               *hexutil.Big    `json:"gasPrice" gencodec:"required"`
		GasLimit            hexutil.Uint64  `json:"gas"      gencodec:"required"`
		FeeCurrency         *common.Address `json:"feeCurrency" rlp:"nil"`
		GatewayFeeRecipient *common.Address `json:"gatewayFeeRecipient" rlp:"nil"`
		GatewayFee          *hexutil.Big    `json:"gatewayFee" rlp:"nil"`
		Recipient           *common.Address `json:"to"       rlp:"nil"`
		Amount              *hexutil.Big    `json:"value"    gencodec:"required"`
		Payload             hexutil.Bytes   `json:"input"    gencodec:"required"`
		V                   *hexutil.Big    `json:"v" gencodec:"required"`
		R                   *hexutil.Big    `json:"r" gencodec:"required"`
		S                   *hexutil.Big    `json:"s" gencodec:"required"`
		Hash                *common.Hash    `json:"hash" rlp:"-"`
	}
	var enc Txdata
	enc.AccountNonce = hexutil.Uint64(t.AccountNonce)
	enc.Price = (*hexutil.Big)(t.Price)
	enc.GasLimit = hexutil.Uint64(t.GasLimit)
	enc.FeeCurrency = t.FeeCurrency
	enc.GatewayFeeRecipient = t.GatewayFeeRecipient
	enc.GatewayFee = (*hexutil.Big)(t.GatewayFee)
	enc.Recipient = t.Recipient
	enc.Amount = (*hexutil.Big)(t.Amount)
	enc.Payload = t.Payload
	enc.V = (*hexutil.Big)(t.V)
	enc.R = (*hexutil.Big)(t.R)
	enc.S = (*hexutil.Big)(t.S)
	enc.Hash = t.Hash
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (t *Txdata) UnmarshalJSON(input []byte) error {
	type Txdata struct {
		AccountNonce        *hexutil.Uint64 `json:"nonce"    gencodec:"required"`
		Price               *hexutil.Big    `json:"gasPrice" gencodec:"required"`
		GasLimit            *hexutil.Uint64 `json:"gas"      gencodec:"required"`
		FeeCurrency         *common.Address `json:"feeCurrency" rlp:"nil"`
		GatewayFeeRecipient *common.Address `json:"gatewayFeeRecipient" rlp:"nil"`
		GatewayFee          *hexutil.Big    `json:"gatewayFee" rlp:"nil"`
		Recipient           *common.Address `json:"to"       rlp:"nil"`
		Amount              *hexutil.Big    `json:"value"    gencodec:"required"`
		Payload             *hexutil.Bytes  `json:"input"    gencodec:"required"`
		V                   *hexutil.Big    `json:"v" gencodec:"required"`
		R                   *hexutil.Big    `json:"r" gencodec:"required"`
		S                   *hexutil.Big    `json:"s" gencodec:"required"`
		Hash                *common.Hash    `json:"hash" rlp:"-"`
	}
	var dec Txdata
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.AccountNonce == nil {
		return errors.New("missing required field 'nonce' for Txdata")
	}
	t.AccountNonce = uint64(*dec.AccountNonce)
	if dec.Price == nil {
		return errors.New("missing required field 'gasPrice' for Txdata")
	}
	t.Price = (*big.Int)(dec.Price)
	if dec.GasLimit == nil {
		return errors.New("missing required field 'gas' for Txdata")
	}
	t.GasLimit = uint64(*dec.GasLimit)
	if dec.FeeCurrency != nil {
		t.FeeCurrency = dec.FeeCurrency
	}
	if dec.GatewayFeeRecipient != nil {
		t.GatewayFeeRecipient = dec.GatewayFeeRecipient
	}
	if dec.GatewayFee != nil {
		t.GatewayFee = (*big.Int)(dec.GatewayFee)
	}
	if dec.Recipient != nil {
		t.Recipient = dec.Recipient
	}
	if dec.Amount == nil {
		return errors.New("missing required field 'value' for Txdata")
	}
	t.Amount = (*big.Int)(dec.Amount)
	if dec.Payload == nil {
		return errors.New("missing required field 'input' for Txdata")
	}
	t.Payload = *dec.Payload
	if dec.V == nil {
		return errors.New("missing required field 'v' for Txdata")
	}
	t.V = (*big.Int)(dec.V)
	if dec.R == nil {
		return errors.New("missing required field 'r' for Txdata")
	}
	t.R = (*big.Int)(dec.R)
	if dec.S == nil {
		return errors.New("missing required field 's' for Txdata")
	}
	t.S = (*big.Int)(dec.S)
	if dec.Hash != nil {
		t.Hash = dec.Hash
	}
	return nil
}
