[package]
name = "epoch-snark"
version = "0.1.0"
authors = ["Kobi Gurkan <kobigurk@gmail.com>", "Michael Straka <mstraka@celo.org>"]
edition = "2018"

[dependencies]
bls-crypto = { path = "../bls-crypto" }
bls-gadgets = { path = "../bls-gadgets" }

algebra = { git = "https://github.com/scipr-lab/zexe", features = ["bls12_377", "sw6", "edwards_sw6", "edwards_bls12", "parallel"] }
r1cs-core = { git = "https://github.com/scipr-lab/zexe" }
r1cs-std = { git = "https://github.com/scipr-lab/zexe", features = ["bls12_377", "edwards_sw6", "edwards_bls12", "parallel"] }
crypto-primitives = { git = "https://github.com/scipr-lab/zexe", features = ["r1cs", "groth16", "parallel"] }
groth16 = { git = "https://github.com/scipr-lab/zexe", features = ["parallel"] }

rand = "0.7" 
byteorder = "1.3.2"
log = "0.4.8"
blake2s_simd = "0.5.8"
thiserror = "1.0.11"
tracing-subscriber = "0.2.3"
tracing = "0.1.13"

[dev-dependencies]
rand_xorshift = { version = "0.2" }
bench-utils = { git = "https://github.com/scipr-lab/zexe", features = ["print-trace"] }
hex = "0.3.2"
bls-gadgets = { path = "../bls-gadgets", features = ["test-helpers"] }

[lib]
crate-type = ["lib", "staticlib"]

[[example]]
name = "proof"
path = "examples/proof.rs"

[[example]]
name = "constraints"
path = "examples/constraints.rs"