// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package genesis

import (
	"encoding/json"
	"math/big"

	"github.com/celo-org/celo-blockchain/common/decimal/bigintstr"
)

var _ = (*DowntimeSlasherParametersMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (d DowntimeSlasherParameters) MarshalJSON() ([]byte, error) {
	type DowntimeSlasherParameters struct {
		Penalty           *bigintstr.BigIntStr `json:"penalty"`
		Reward            *bigintstr.BigIntStr `json:"reward"`
		SlashableDowntime uint64               `json:"slashableDowntime"`
	}
	var enc DowntimeSlasherParameters
	enc.Penalty = (*bigintstr.BigIntStr)(d.Penalty)
	enc.Reward = (*bigintstr.BigIntStr)(d.Reward)
	enc.SlashableDowntime = d.SlashableDowntime
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (d *DowntimeSlasherParameters) UnmarshalJSON(input []byte) error {
	type DowntimeSlasherParameters struct {
		Penalty           *bigintstr.BigIntStr `json:"penalty"`
		Reward            *bigintstr.BigIntStr `json:"reward"`
		SlashableDowntime *uint64              `json:"slashableDowntime"`
	}
	var dec DowntimeSlasherParameters
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Penalty != nil {
		d.Penalty = (*big.Int)(dec.Penalty)
	}
	if dec.Reward != nil {
		d.Reward = (*big.Int)(dec.Reward)
	}
	if dec.SlashableDowntime != nil {
		d.SlashableDowntime = *dec.SlashableDowntime
	}
	return nil
}
