---
name: 'Run Go Tests'
on:
  workflow_call:
    inputs:
      go-version:
        required: false
        type: string
        default: "1.19.5"
      path:
        required: true
        type: string

env:
  GO_VERSION: ${{ inputs.go-version }}
  GO_WORKING_DIRECTORY: ${{ inputs.path }}

jobs:
  go-tests:
    runs-on: ubuntu-latest
    permissions: # Must change the job token permissions to use JWT auth
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3
         
      - name: Set up Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Verify dependencies
        working-directory: ${{ env.GO_WORKING_DIRECTORY  }}
        run: go mod verify

      - name: Build
        working-directory: ${{ env.GO_WORKING_DIRECTORY  }}
        run: go build -v ./...

      - name: Run go vet
        working-directory: ${{ env.GO_WORKING_DIRECTORY  }}
        run: go vet ./...

      - name: Install staticcheck
        working-directory: ${{ env.GO_WORKING_DIRECTORY  }}
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        working-directory: ${{ env.GO_WORKING_DIRECTORY }}
        run: staticcheck ./...

      - name: Install golint
        working-directory: ${{ env.GO_WORKING_DIRECTORY }} 
        run: go install golang.org/x/lint/golint@latest

      - name: Run golint
        working-directory: ${{ env.GO_WORKING_DIRECTORY }} 
        run: golint ./...

      - name: Run tests
        working-directory: ${{ env.GO_WORKING_DIRECTORY }}
        run: go test -race -vet=off -v ./...


